services:
  nextjs:
    image: node:20-alpine
    container_name: home-ui
    working_dir: /app
    ports:
      - "3001:3000"   # host:container
    volumes:
      - .:/app
      - node_node_modules:/app/node_modules
    environment:
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev && npx update-browserslist-db@latest"

volumes:
  node_node_modules:
